# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import vpn_node_pb2 as vpn__node__pb2
except ImportError:
    import vpn_node_pb2 as vpn__node__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vpn_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VpnNodeControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterVpnNode = channel.unary_unary(
                '/vpn.vpn_node.VpnNodeControlService/RegisterVpnNode',
                request_serializer=vpn__node__pb2.RegisterVpnNodeRequest.SerializeToString,
                response_deserializer=vpn__node__pb2.RegisterVpnNodeResponse.FromString,
                _registered_method=True)
        self.WatchDesiredState = channel.unary_stream(
                '/vpn.vpn_node.VpnNodeControlService/WatchDesiredState',
                request_serializer=vpn__node__pb2.WatchDesiredStateRequest.SerializeToString,
                response_deserializer=vpn__node__pb2.DesiredStateEnvelope.FromString,
                _registered_method=True)
        self.ReportActualState = channel.unary_unary(
                '/vpn.vpn_node.VpnNodeControlService/ReportActualState',
                request_serializer=vpn__node__pb2.ReportActualStateRequest.SerializeToString,
                response_deserializer=vpn__node__pb2.ReportActualStateResponse.FromString,
                _registered_method=True)
        self.ReportHeartbeat = channel.unary_unary(
                '/vpn.vpn_node.VpnNodeControlService/ReportHeartbeat',
                request_serializer=vpn__node__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=vpn__node__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class VpnNodeControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterVpnNode(self, request, context):
        """Agent registers identity and capabilities upon booting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchDesiredState(self, request, context):
        """Persistent streaming RPC where controller pushes desired states to agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportActualState(self, request, context):
        """Agent acknowledges and reports actual reconciled state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHeartbeat(self, request, context):
        """Periodic heartbeat reporting CPU, memory, active WireGuard peers, and version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VpnNodeControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterVpnNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterVpnNode,
                    request_deserializer=vpn__node__pb2.RegisterVpnNodeRequest.FromString,
                    response_serializer=vpn__node__pb2.RegisterVpnNodeResponse.SerializeToString,
            ),
            'WatchDesiredState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchDesiredState,
                    request_deserializer=vpn__node__pb2.WatchDesiredStateRequest.FromString,
                    response_serializer=vpn__node__pb2.DesiredStateEnvelope.SerializeToString,
            ),
            'ReportActualState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportActualState,
                    request_deserializer=vpn__node__pb2.ReportActualStateRequest.FromString,
                    response_serializer=vpn__node__pb2.ReportActualStateResponse.SerializeToString,
            ),
            'ReportHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHeartbeat,
                    request_deserializer=vpn__node__pb2.HeartbeatRequest.FromString,
                    response_serializer=vpn__node__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vpn.vpn_node.VpnNodeControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vpn.vpn_node.VpnNodeControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VpnNodeControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterVpnNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpn.vpn_node.VpnNodeControlService/RegisterVpnNode',
            vpn__node__pb2.RegisterVpnNodeRequest.SerializeToString,
            vpn__node__pb2.RegisterVpnNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchDesiredState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vpn.vpn_node.VpnNodeControlService/WatchDesiredState',
            vpn__node__pb2.WatchDesiredStateRequest.SerializeToString,
            vpn__node__pb2.DesiredStateEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportActualState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpn.vpn_node.VpnNodeControlService/ReportActualState',
            vpn__node__pb2.ReportActualStateRequest.SerializeToString,
            vpn__node__pb2.ReportActualStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpn.vpn_node.VpnNodeControlService/ReportHeartbeat',
            vpn__node__pb2.HeartbeatRequest.SerializeToString,
            vpn__node__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
